# Generated by Django 6.0.3 on 2026-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanIMDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=100)),
                ('content_rating', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('income', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawIMDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=100)),
                ('content_rating', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('income', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CleanStudent',
        ),
    ]
